Repository prgrms-fe-devcourse/NFE1_2_3_Clogging, pull requests merged in 2024-11, with the labels that each got.

#57 Feat: admin 카테고리 관리 데이터 연동
  clogging/src/app/(auth)/admin/category/page.tsx
  clogging/src/app/api/categories/create/route.ts
  clogging/src/app/api/categories/reorder/route.ts
  clogging/src/app/api/categories/update/[id]/route.ts
  clogging/src/features/Category/hooks.ts
  clogging/src/features/Category/types.ts
  clogging/src/features/Category/ui/admin/CategoryForm.tsx
  clogging/src/features/Category/ui/admin/CategoryItem.tsx
  clogging/src/features/Category/ui/admin/CategoryList.tsx
  clogging/src/features/Category/ui/admin/CategoryManagement.tsx
  clogging/src/features/Category/ui/admin/CategoryOrderList.tsx
Labels: ✨ Feature

#61 🐛 Fix : 카테고리 추가 오류, 순서변경 오류 수정
  clogging/src/app/(auth)/admin/category/page.tsx
  clogging/src/features/Category/hooks.ts
  clogging/src/features/Category/ui/admin/CategoryForm.tsx
  clogging/src/features/Category/ui/admin/CategoryManagement.tsx
  clogging/src/features/Category/ui/admin/CategoryOrderList.tsx
Labels: 🐛 Fix

#63 Feat: 댓글 api 연동
  clogging/src/features/Comment/api/Reply/replyApi.ts
  clogging/src/features/Comment/api/Reply/useReply.ts
  clogging/src/features/Comment/api/commentApi.ts
  clogging/src/features/Comment/api/useCommentCount.ts
  clogging/src/features/Comment/api/useComments.ts
  clogging/src/features/Comment/lib/stores/useCommentFormStore.ts
  clogging/src/features/Comment/lib/stores/useCommentListStore.ts
  clogging/src/features/Comment/lib/utils/commentUtils.ts
  clogging/src/features/Comment/types.ts
  clogging/src/features/Comment/ui/CommentForm.tsx
  clogging/src/features/Comment/ui/CommentItem.tsx
  clogging/src/features/Comment/ui/CommentList.tsx
  clogging/src/features/Comment/ui/InputComment.tsx
  clogging/src/features/Post/ui/Card/PostCard.tsx
  clogging/src/features/Post/ui/Detail/Content.tsx
  clogging/src/features/Post/ui/Detail/Header.tsx
  clogging/src/features/Post/ui/Detail/Navigation.tsx
  clogging/src/features/Post/ui/Detail/index.tsx
  clogging/src/mocks/data/comments.ts
  clogging/src/mocks/data/posts.ts
  clogging/src/mocks/handlers/commentApi.ts
Labels: ✨ Feature

#64 ✨ Feat: 게시물 상세 페이지 본문에 목차 확인 및 이동 기능 추가
  clogging/next.config.js
  clogging/src/features/Post/ui/Detail/Content.tsx
  clogging/src/features/Post/ui/Detail/index.tsx
  clogging/src/features/Post/ui/TableOfContents.tsx
Labels: ✨ Feature

#62 Feat: 포스트 작성 페이지 마크업
  clogging/package.json
  clogging/pnpm-lock.yaml
  clogging/src/app/(auth)/posting/page.tsx
  clogging/src/features/Post/lib/hooks/usePostEditor.ts
  clogging/src/features/Post/ui/Posting/PostEditor.tsx
Labels: ✨ Feature

#66 Feat: 통계 데이터 반영
  clogging/package.json
  clogging/pnpm-lock.yaml
  clogging/src/app/(auth)/admin/analytics/page.tsx
  clogging/src/app/(auth)/admin/page.tsx
  clogging/src/features/Admin/Analytics/hooks/getBlogData.ts
  clogging/src/features/Admin/Analytics/types.ts
  clogging/src/features/Admin/Analytics/ui/BlogAnalytics.tsx
  clogging/src/features/Admin/Analytics/ui/BlogDataCard.tsx
  clogging/src/features/Admin/Analytics/ui/BlogDataList.tsx
  clogging/src/features/Admin/Analytics/ui/CustomBarChart.tsx
  clogging/src/features/Admin/Analytics/ui/CustomLineChart.tsx
  clogging/src/features/Admin/Analytics/ui/PostingCalendar.tsx
  clogging/src/features/Admin/Analytics/utils/statisticsHelpers.ts
  clogging/src/features/Admin/Blog-settings/ui/FaviconImageField.tsx
  clogging/src/features/Admin/Blog-settings/ui/ProfileImageField.tsx
  clogging/src/features/Admin/Blog-settings/ui/SettingTextField.tsx
  clogging/src/features/Admin/Blog-settings/ui/SettingsForm.tsx
  clogging/src/features/Admin/Blog-settings/ui/bannerImageField.tsx
  clogging/src/features/Admin/types.ts
  clogging/src/features/Admin/ui/analytics/AreaChart.tsx
  clogging/src/features/Admin/ui/analytics/BlogAnalytics.tsx
  clogging/src/features/Admin/ui/analytics/BlogDataCard.tsx
  clogging/src/features/Admin/ui/analytics/LineChart.tsx
  clogging/src/features/Admin/ui/analytics/PostingCalendar.tsx
Labels: ✨ Feature

#68 Feat: 피드 페이지 API 연결
  clogging/src/app/(auth)/admin/blog-settings/page.tsx
  clogging/src/app/(auth)/posts/page.tsx
  clogging/src/app/feed/page.tsx
  clogging/src/app/posts/[id]/page.tsx
  clogging/src/app/posts/page.tsx
  clogging/src/features/Category/hooks.ts
  clogging/src/features/Category/ui/CategorySection.tsx
  clogging/src/features/Post/hooks.ts
  clogging/src/features/Post/ui/Card/HorizontalPostCard.tsx
  clogging/src/features/Post/ui/Card/PostCard.tsx
  clogging/src/shared/ui/layout/Navigation.tsx
Labels: ✨ Feature

#71 🐛 Fix: 댓글 수정, 삭제 시 비밀번호 인증 로직 수정 [#70]
  clogging/next.config.js
  clogging/src/features/Comment/ui/CommentList.tsx
  clogging/src/features/Comment/utils/findCommentLevel.ts
  clogging/src/features/Comment/utils/findParentComment.ts
  clogging/src/features/Comment/utils/verifyPassword.ts
Labels: 🐛 Fix

#72 Feat: 검색 페이지 구현
  clogging/src/app/api/search/route.ts
  clogging/src/app/search/page.tsx
  clogging/src/features/Search/hooks.ts
  clogging/src/shared/ui/Form/SearchBar.tsx
Labels: ✨ Feature

#74 ✨ Feat: 유저 상태에 따른 댓글 비공개 처리 [#73]
  clogging/src/app/api/comments/create/route.ts
  clogging/src/app/api/comments/replies/create/route.ts
  clogging/src/app/api/comments/replies/update/route.ts
  clogging/src/app/api/comments/update/route.ts
  clogging/src/features/Comment/api/Reply/replyApi.ts
  clogging/src/features/Comment/api/Reply/useReply.ts
  clogging/src/features/Comment/api/commentApi.ts
  clogging/src/features/Comment/api/useComments.ts
  clogging/src/features/Comment/lib/stores/useCommentFormStore.ts
  clogging/src/features/Comment/ui/CommentForm.tsx
  clogging/src/features/Comment/ui/CommentItem.tsx
  clogging/src/features/Comment/ui/CommentList.tsx
  clogging/src/features/Comment/ui/InputComment.tsx
Labels: ✨ Feature

#75 Feat: 블로그 관리 페이지 데이터 저장
  clogging/cors.json
  clogging/src/app/(auth)/admin/blog-settings/page.tsx
  clogging/src/app/api/settings/route.ts
  clogging/src/app/layout.tsx
  clogging/src/features/Admin/Blog-settings/hooks/useFetchSettings.ts
  clogging/src/features/Admin/Blog-settings/hooks/useUploadImages.ts
  clogging/src/features/Admin/Blog-settings/types.ts
  clogging/src/features/Admin/Blog-settings/ui/FaviconImageField.tsx
  clogging/src/features/Admin/Blog-settings/ui/ProfileImageField.tsx
  clogging/src/features/Admin/Blog-settings/ui/SettingsDisplay.tsx
  clogging/src/features/Admin/Blog-settings/ui/SettingsForm.tsx
  clogging/src/features/Admin/Blog-settings/ui/bannerImageField.tsx
Labels: ✨ Feature

#77 Feat: 관리자 비밀번호 설정 및 관리 기능 추가
  clogging/src/app/(admin)/admin/init/layout.tsx
  clogging/src/app/(admin)/admin/init/page.tsx
  clogging/src/app/(auth)/admin/admin-settings/page.tsx
  clogging/src/app/(auth)/admin/layout.tsx
  clogging/src/app/ClientLayout.tsx
  clogging/src/app/api/admin/init/route.ts
  clogging/src/app/api/admin/password/route.ts
  clogging/src/app/api/admin/reset/route.ts
  clogging/src/app/api/admin/route.ts
  clogging/src/app/api/admin/update-password/route.ts
  clogging/src/app/api/admin/verify/route.ts
  clogging/src/app/layout.tsx
  clogging/src/app/page.tsx
  clogging/src/features/Admin/Blog-settings/ui/SettingPassword.tsx
  clogging/src/features/Admin/api/adminApi.ts
  clogging/src/features/Admin/hooks/useAuth.ts
  clogging/src/features/Admin/stores/useAdminStore.ts
  clogging/src/features/Admin/ui/AdminAuth.tsx
  clogging/src/shared/ui/layout/Navigation.tsx
Labels: ✨ Feature

#79 Feat: admin 페이지 댓글삭제 수정
  clogging/src/app/(auth)/admin/comment/page.tsx
  clogging/src/features/Comment/api/getAllComments.ts
  clogging/src/features/Comment/ui/CommentList.tsx
  clogging/src/features/Comment/ui/admin/CommentItem.tsx
  clogging/src/features/Comment/ui/admin/CommentList.tsx
  clogging/src/features/Comment/ui/admin/ReplyItem.tsx
  clogging/src/features/Comment/ui/admin/ReplyList.tsx
  clogging/src/features/Comment/utils/adminDeleteComment.ts
  clogging/src/features/Comment/utils/adminDeleteReply.ts
  clogging/src/features/Comment/utils/dailyCommentCount.ts
  clogging/src/features/Comment/utils/dateUtils.ts
  clogging/src/features/Comment/utils/recentComment.ts
  clogging/src/shared/lib/utils/formatDateTime.ts
Labels: ✨ Feature

#83 Feat: 관리 페이지 배너, 이미지 등 저장상태 확인 및 홈 ,피드 페이지에 연결
  clogging/src/app/posts/page.tsx
  clogging/src/features/Profile/ui/Section.tsx
Labels: ✨ Feature

#84 Feat:admin 메인대시보드
  clogging/src/app/(auth)/admin/comment/page.tsx
  clogging/src/app/(auth)/admin/page.tsx
  clogging/src/features/Admin/Analytics/hooks/getBlogData.ts
  clogging/src/features/Admin/Analytics/types.ts
  clogging/src/features/Admin/Analytics/ui/BlogDataCard.tsx
  clogging/src/features/Admin/Analytics/ui/BlogDataList.tsx
  clogging/src/features/Admin/Dashboard/ui/BlogDataSection.tsx
  clogging/src/features/Admin/Dashboard/ui/CommentSection.tsx
  clogging/src/features/Admin/Dashboard/ui/LoadingError.tsx
  clogging/src/features/Admin/Dashboard/ui/PostListSection.tsx
  clogging/src/features/Comment/ui/admin/CommentItem.tsx
  clogging/src/features/Comment/ui/admin/CommentList.tsx
Labels: ✨ Feature

#89 Fix: 런타임 에러 및 카테고리 연동 수정
  clogging/src/app/posts/page.tsx
  clogging/src/features/Category/ui/CategorySection.tsx
  clogging/src/features/Comment/api/useCommentCount.ts
  clogging/src/features/Post/types.ts
  clogging/src/features/Post/ui/Card/HorizontalPostCard.tsx
  clogging/src/features/Post/ui/Card/PostCard.tsx
Labels: 🐛 Fix

#90 🐛 Fix : 블로그 통계 데이터 오류 수정
  clogging/src/app/(auth)/admin/analytics/page.tsx
  clogging/src/app/(auth)/admin/page.tsx
  clogging/src/features/Admin/Analytics/types.ts
  clogging/src/features/Admin/Analytics/utils/getBlogData.ts
  clogging/src/features/Admin/Dashboard/utils/getRecentPosts.ts
Labels: 🐛 Fix

#92 Feat: 포스트 작업 페이지 구현 (2)
  clogging/package.json
  clogging/pnpm-lock.yaml
  clogging/src/app/api/posts/create/route.ts
  clogging/src/app/api/posts/route.ts
  clogging/src/features/Post/lib/hooks/useMarkdown.ts
  clogging/src/features/Post/lib/hooks/usePostEditor.ts
  clogging/src/features/Post/ui/Posting/PostEditor.tsx
  clogging/src/features/Post/utils/helpers.ts
Labels: ✨ Feature, 🐛 Fix

#95 🐛 Fix: 상세 페이지에 카테고리 실제로 적용되도록 수정
  clogging/src/features/Post/ui/Detail/Header.tsx
Labels: 🐛 Fix

#97 Feat: 상세 포스팅 마크다운 적용 #93
  clogging/src/features/Post/ui/Detail/Content.tsx
Labels: ✨ Feature

#99 Fix: 블로그 관리 ui 수정
  clogging/src/app/(auth)/admin/blog-settings/page.tsx
  clogging/src/app/layout.tsx
  clogging/src/features/Admin/Blog-settings/constants.ts
  clogging/src/features/Admin/Blog-settings/hooks/getFaviconUrl.ts
  clogging/src/features/Admin/Blog-settings/hooks/useFetchSettings.ts
  clogging/src/features/Admin/Blog-settings/hooks/useImageHandling.ts
  clogging/src/features/Admin/Blog-settings/types.ts
  clogging/src/features/Admin/Blog-settings/ui/FaviconImageField.tsx
  clogging/src/features/Admin/Blog-settings/ui/ProfileImageField.tsx
  clogging/src/features/Admin/Blog-settings/ui/SettingTextField.tsx
  clogging/src/features/Admin/Blog-settings/ui/SettingsDisplay.tsx
  clogging/src/features/Admin/Blog-settings/ui/SettingsForm.tsx
  clogging/src/features/Admin/Blog-settings/ui/bannerImageField.tsx
Labels: ✨ Feature, 🐛 Fix

#100 Fix: 다크모드에서 상세페이지 색 수정
  clogging/src/features/Comment/ui/CommentItem.tsx
  clogging/src/features/Post/ui/Detail/Header.tsx
  clogging/src/features/Post/ui/Detail/Navigation.tsx
Labels: 🐛 Fix

#109 Fix: 피드 페이지 태그 로직 수정 및 반응형 구현
  clogging/src/app/posts/page.tsx
  clogging/src/features/Post/ui/Card/HorizontalPostCard.tsx
  clogging/src/features/Tag/hooks.ts
Labels: 🐛 Fix

#110 Feat: admin 댓글관리 포스트 이동, 카테고리 이름 수정 기능
  clogging/src/app/(auth)/admin/comment/page.tsx
  clogging/src/app/api/comments/replies/[id]/delete-without-pw/route.ts
  clogging/src/features/Admin/Dashboard/ui/CommentSection.tsx
  clogging/src/features/Admin/Dashboard/ui/PostListSection.tsx
  clogging/src/features/Admin/Dashboard/ui/PostTable.tsx
  clogging/src/features/Admin/ui/MainContent.tsx
  clogging/src/features/Admin/ui/SideBar.tsx
  clogging/src/features/Category/ui/admin/CategoryForm.tsx
  clogging/src/features/Category/ui/admin/CategoryItem.tsx
  clogging/src/features/Category/ui/admin/CategoryList.tsx
  clogging/src/features/Category/ui/admin/CategoryManagement.tsx
  clogging/src/features/Comment/ui/admin/CommentItem.tsx
  clogging/src/features/Comment/ui/admin/CommentList.tsx
  clogging/src/features/Comment/ui/admin/ReplyList.tsx
  clogging/src/features/Comment/utils/adminDeleteReply.ts
  clogging/src/features/Comment/utils/dailyCommentCount.ts
  clogging/src/features/Comment/utils/dateUtils.ts
Labels: ✨ Feature

#111 Fix: 포스팅 이미지 모든 이슈 해결하기
  clogging/src/features/Post/lib/hooks/usePostEditor.ts
  clogging/src/features/Post/ui/Detail/Content.tsx
  clogging/src/features/Post/ui/Posting/PostEditor.tsx
  clogging/src/features/Post/ui/edit/EditPostEditor.tsx
Labels: 🐛 Fix

#114 Feat: 마크다운 적용 후 목차 기능 로직 수정 및 전체적으로 반응형 작업
  clogging/src/app/(admin)/admin/init/page.tsx
  clogging/src/app/ClientLayout.tsx
  clogging/src/app/api/comments/route.ts
  clogging/src/app/home/page.tsx
  clogging/src/app/posts/page.tsx
  clogging/src/app/search/page.tsx
  clogging/src/features/Admin/Blog-settings/ui/SettingPassword.tsx
  clogging/src/features/Comment/ui/CommentItem.tsx
  clogging/src/features/Post/ui/Card/HorizontalPostCard.tsx
  clogging/src/features/Post/ui/Detail/Content.tsx
  clogging/src/features/Post/ui/Detail/Header.tsx
  clogging/src/features/Post/ui/Detail/Navigation.tsx
  clogging/src/features/Post/ui/Detail/index.tsx
  clogging/src/features/Post/ui/Posting/PostEditor.tsx
  clogging/src/features/Post/ui/TableOfContents.tsx
  clogging/src/features/Post/ui/edit/EditPostEditor.tsx
  clogging/src/shared/ui/common/Badge.tsx
  clogging/src/shared/ui/common/Card.tsx
  clogging/src/shared/ui/layout/HomeStyleWrapper.tsx
  clogging/src/shared/ui/layout/Navigation.tsx
Labels: ✨ Feature, 🐛 Fix, 💄 Style

#115 Fix: 태그 5개 초과 alert 출력 #112
  clogging/src/features/Post/ui/Posting/PostEditor.tsx
Labels: ✨ Feature, 🐛 Fix

#118 ✨ Feat: 로딩 애니메이션 추가"
  clogging/src/app/(admin)/admin/init/page.tsx
  clogging/src/app/(auth)/admin/category/page.tsx
  clogging/src/app/(auth)/admin/comment/page.tsx
  clogging/src/app/ClientLayout.tsx
  clogging/src/app/home/page.tsx
  clogging/src/app/posts/[id]/page.tsx
  clogging/src/app/posts/page.tsx
  clogging/src/app/search/page.tsx
  clogging/src/features/Category/ui/admin/CategoryManagement.tsx
  clogging/src/features/Post/ui/Detail/index.tsx
  clogging/src/features/Post/ui/Posting/PostEditor.tsx
  clogging/src/features/Post/ui/edit/EditPostEditor.tsx
Labels: ✨ Feature

#119 Fix: 줄바꿈 테스트 #116
  clogging/package.json
  clogging/pnpm-lock.yaml
  clogging/src/features/Post/ui/Detail/Content.tsx
  clogging/src/features/Post/ui/Posting/PostEditor.tsx
  clogging/src/features/Post/ui/edit/EditPostEditor.tsx
Labels: 🐛 Fix

#120 🐛 Fix : admin댓글삭제 마지막페이지 오류 수정
  clogging/src/features/Admin/Dashboard/ui/PostListSection.tsx
  clogging/src/features/Comment/ui/admin/CommentList.tsx
Labels: 🐛 Fix
